name: Snyk Infrastructure as Code Security Scan

on:
  pull_request:

jobs:
  snyk-iac-security:
    name: Run Snyk IaC Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check Kubernetes manifest file for issues
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: .
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
      - name: comment PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Check out this message!"
          check_for_duplicate_msg: false  # OPTIONAL 