name: Snyk Infrastructure as Code Security Scan

on:
  pull_request:

env:
  # Set the severity threshold to block the build on
  # the value can be low | medium | high | critical
  severity_threshold: medium

jobs:
  snyk-iac-security:
    name: Scan & Upload IaC results
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk IaC
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: .
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
  snyk-iac-block:
    name: Update PR & Block Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk IaC
        id: iac
        continue-on-error: false
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: .
          args: --severity-threshold=${{ env.severity_threshold }}
      - name: PR Comment - Success
        if: ${{ success() }}
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "No ${{ env.severity_threshold }} or higher issues were found"
          check_for_duplicate_msg: false  # OPTIONAL 
      - name: PR Comment - Failure
        if: ${{ failure() }}
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "We found ${{ env.severity_threshold }} or higher issues"
          check_for_duplicate_msg: false  # OPTIONAL 